### ISSUE TITLE
Replace the "Reply" button and popup with an embedded reply panel in forum threads

### ISSUE THREAD

**Issue by rgilman** [ContextInstitute/brightfuturecommons#26]
As a temporary measure, I moved the Reply button from the right sidebar to the bottom of the thread. That makes the thread usable but I'd rather remove the step of needing to click the button before you start a reply.

Their design is set up so you can start a reply anywhere in the thread and the popup will appear where you are. I see that enabling fragmented conversations, where someone make a reply to a post without reading what's come after it. I would rather have the reply panel fixed at the end of the thread to encourage replies that take the whole conversation into account.

I assume there is some template the generates the reply popup panel. We should be able stick this at the bottom of the thread.

**Comment by iangilman** [comment]
I'm happy if you are :-)
