### ISSUE TITLE
Create "like" system for forum posts similar to what exists for activity posts

### ISSUE THREAD

**Issue by rgilman** [ContextInstitute/brightfuturecommons#42]
Activity items have a quite nice "like" system. We need to create a similar system for forum posts if we are to match what exists in Xenforo.

![Screen Shot 2022-01-23 at 5 42 55 PM](https://user-images.githubusercontent.com/615052/150708952-69edbc11-ab01-4d83-8cc0-f2f32a51d107.png)

(Activity items also have threaded comments but we don't want that for forum posts.)

From what I can tell, the functions that run the "like" system are in `/wp-content/plugins/buddyboss-platform/bp-activity/bp-activity-functions.php`, starting at line 902 under the heading of "Favorites" and going down to line 1246 and `/wp-content/plugins/buddyboss-platform/bp-templates/bp-nouveau/js/buddypress-activity.js`, starting at line 695 under the heading of "Favoriting" and going down to line 760.

I'm hopeful that we can copy these functions and tweak them to work for forum posts.

The data that tracks who likes which activity post is stored in` wp_bp_activity_meta` as serialized data with the meta_key of `bp_favorite_users`. Also stored is `favorite_count`.

Forum posts are stored as regular WordPress posts in `wp_posts`. They have a similar companion table called `wp_postmeta` with the same table structure as `wp_bp_activity_meta`.

I've been puzzled about why activity items had this well developed system and forum posts had nothing. It doesn't make much sense for our use case. However, I'm starting to see how the development history may have lead here.

The functions in `bp-activity-functions.php` are really old, dating back to BuddyPress 1.0.0. I think that's at least 10 years ago. bbPress was developed separately and is a bit younger. It looks like the bbPress developers never created a "like" system.

In the BuddyBoss Platform, BuddyPress and bbPress are combined into what seems like an integrated system but it's made of components with different histories.

**Comment by iangilman** [comment]
It seems like it might be worth engaging with the BuddyBoss folks (at least checking their GitHub or whatever) to see if there is any development underway on this front.

**Comment by rgilman** [comment]
Good idea. I've queried their tech support to see if this is underway.

**Comment by rgilman** [comment]
I've heard back from them and I thought the exchange was worth sharing.

I wrote:

> We're thinking of creating a "like" system for forum posts similar to what exists for activity posts but before we do, we'd like to know if the BuddyBoss team is already working on this.
> 
> In https://portal.productboard.com/ovnj9nspjap9l4fra3uzwu6k/c/103-improve-the-forum-experience, Mike Young talks about "significant improvements to the overall forum experience". Is such a "like" system for forum posts part of this? If so, when might it be released?  Thanks!
> 

The response was:

> Hi Robert.
> ​
> Good day. Hope you're doing well.
> 
> This feature https://portal.productboard.com/ovnj9nspjap9l4fra3uzwu6k/c/103-improve-the-forum-experience which is listed in the "planned" category is what we're planning to do, but how the feature will exactly work or when it will be released is currently unknown. Please be advised that we have not currently made a final decision which of these are higher priority than others and we may end up not making these features - as we add new features, we may decide to change direction.
> ​
> Hoping for your understanding.
> 
> Please feel free to email us if you have any questions. Take care.
> 
> Kind regards,
> Angelic - BuddyBoss Support

Looks like were on our own. ;-)

**Comment by brandevnull** [comment]
Doing first poking around this.

Forum posts currently have the notion of 'favorites'. This functionality is invoked via the yellow star icon when on the forum topic page and feels more like bookmarking a post rather than a typical 'like' feature.

The data here is saved in table `wp_usermeta`, meta_key `wp__bbp_favorites`. The value here is a list of post ids the user likes. So the data is meant to power a list of stuff the user likes rather than a list of users that liked the post.

Question: Is this favoriting/bookmarking behavior desired in its current form? Or would we feel OK about repurposing it to feel more like a 'like'?

**Comment by rgilman** [comment]
@brandevnull, that's great. Thanks for looking into this.

As for repurposing the _favoriting/bookmarking_ behavior, I'm not particular attached to the current function but that function feels quite different from the _like_ function on activity feed posts. As you say, it's a bookmark for a whole thread rather than something attached to a post.

On the other hand, the _like_ function for activity feed posts has all the features I think we'd want in a _like_ function for forum posts. If you haven't played around with it on an activity feed yet, you might look at https://com.context.org/members/steve/activity/226/. That why I've been thinking we would repurpose the _like_ function for activity feed posts.

How does that sound to you?

**Comment by rgilman** [comment]
Addressed with #59
